# Generated by Django 6.0.6 on 2026-06-24 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_alter_perfilempleado_id_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('mesero', 'Mesero'), ('cajero', 'Cajero'), ('pastelero', 'Pastelero'), ('panadero', 'Panadero'), ('cocina', 'Cocina'), ('buñuelero', 'Buñuelero'), ('greca', 'Greca')], max_length=30)),
                ('turno', models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('FIJO', 'Fijo')], max_length=10)),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('dias_laborales', models.JSONField(default=list)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='usuarios.perfilempleado')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('COMPLETO', 'Completo'), ('RETARDO', 'Retardo'), ('AUSENTE', 'Ausente'), ('EN_TURNO', 'En turno')], default='EN_TURNO', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='usuarios.perfilempleado')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.horario')),
            ],
        ),
    ]
