# Generated by Django 6.0.6 on 2026-06-25 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(blank=True, choices=[('PRESENTE', 'Presente'), ('TARDE', 'Tarde'), ('AUSENTE', 'Ausente')], max_length=10, null=True)),
                ('hora_marcada', models.TimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='asistencia.horario')),
            ],
            options={
                'unique_together': {('horario', 'fecha')},
            },
        ),
    ]
