# Generated by Django 6.0.6 on 2026-08-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='ciclo_inicio',
            field=models.DateField(blank=True, help_text='Fecha en que arrancó el ciclo de descanso vigente.', null=True),
        ),
    ]
