# Generated by Django 6.0.6 on 2026-06-24 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        ('usuarios', '0006_alter_perfilempleado_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='horario',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfilempleado'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='turno',
            field=models.CharField(choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde')], max_length=10),
        ),
    ]
