# Generated by Django 4.2.24 on 2026-09-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_horario_ciclo_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha en que finaliza la asignación del horario.', null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha en que inicia la asignación del horario.', null=True),
        ),
    ]
