# Generated by Django 4.2.24 on 2026-09-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_horario_fecha_fin_horario_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='descansoempleado',
            name='fue_generado_automaticamente',
            field=models.BooleanField(default=False, help_text='True si esta fecha de descanso fue calculada por el sistema al generar un nuevo ciclo automáticamente.'),
        ),
        migrations.AddField(
            model_name='horario',
            name='ciclo_anterior',
            field=models.ForeignKey(blank=True, help_text='Ciclo (Horario) del cual este es la continuación automática.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclos_siguientes', to='asistencia.horario'),
        ),
        migrations.AddField(
            model_name='horario',
            name='dia_descanso_semana',
            field=models.IntegerField(blank=True, help_text='0=Lunes...6=Domingo. Solo aplica a turno FIJO: el día de descanso se repite siempre en este día de la semana en cada ciclo.', null=True),
        ),
        migrations.AddField(
            model_name='horario',
            name='es_ciclo_cerrado',
            field=models.BooleanField(default=False, help_text='True cuando este ciclo ya venció y fue reemplazado por el siguiente.'),
        ),
        migrations.AddField(
            model_name='horario',
            name='es_generado_automaticamente',
            field=models.BooleanField(default=False, help_text='True si este Horario fue creado por el sistema (no manualmente por el admin).'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='ciclo_inicio',
            field=models.DateField(blank=True, help_text='Fecha en que arrancó el ciclo vigente de este horario.', null=True),
        ),
    ]
