# Generated by Django 4.2.24 on 2026-09-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_descansoempleado_fue_generado_automaticamente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='minutos_tarde',
            field=models.PositiveIntegerField(blank=True, help_text='Minutos de tardanza. Solo aplica cuando estado=TARDE.', null=True),
        ),
    ]
