# Generated by Django 4.2.24 on 2026-09-18 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorandos', '0001_initial'),
        ('asistencia', '0004_descansoempleado_fue_generado_automaticamente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='memorando_generado',
            field=models.ForeignKey(blank=True, help_text='Memorando generado automáticamente por acumulación de tardanzas o ausencias.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_origen', to='memorandos.memorando'),
        ),
    ]
