# Generated by Django 6.0.6 on 2026-06-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='dirigido_a',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='periodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incapacidad',
            name='entidad_emisora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incapacidad',
            name='numero_incapacidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incapacidad',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='tipo',
            field=models.CharField(choices=[('personal', 'Permiso personal'), ('cambio_turno', 'Cambio de turno'), ('medico', 'Cita médica'), ('familiar', 'Asunto familiar'), ('vacaciones', 'Vacaciones'), ('academico', 'Académico'), ('calamidad', 'Calamidad doméstica'), ('otro', 'Otro')], max_length=20),
        ),
    ]
