# Generated by Django 4.2 on 2026-07-02 12:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='decision_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='decision_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_decididos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='certificado',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 2, 12, 10, 38, 877127, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificado',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
