# Generated by Django 6.0.6 on 2026-06-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_certificado_dirigido_a_certificado_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='tipo',
            field=models.CharField(choices=[('laboral', 'Laboral'), ('ingresos', 'Ingresos'), ('antiguedad', 'Antigüedad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='permiso',
            name='tipo',
            field=models.CharField(choices=[('personal', 'Personal'), ('cambio_turno', 'Cambio de turno'), ('medico', 'Médico'), ('familiar', 'Familiar'), ('vacaciones', 'Vacaciones'), ('academico', 'Académico'), ('calamidad', 'Calamidad'), ('otro', 'Otro')], max_length=20),
        ),
    ]
