# Generated by Django 4.2.24 on 2026-07-21 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novedades', '0002_certificado_decision_fecha_certificado_decision_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memorando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamado_atencion', 'Llamado de atención'), ('amonestacion', 'Amonestación escrita'), ('reconocimiento', 'Reconocimiento'), ('informacion', 'Información general'), ('advertencia', 'Advertencia'), ('cambio_funciones', 'Cambio de funciones'), ('otro', 'Otro')], max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('consecutivo', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('anulado', 'Anulado')], default='emitido', max_length=10)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='memorandos/')),
                ('descargas', models.PositiveIntegerField(default=0)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorandos', to='usuarios.perfilempleado')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memorandos_generados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
