# Generated by Django 6.0.6 on 2026-07-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0003_memorando'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memorando',
        ),
    ]
