# Generated by Django 4.2.24 on 2026-08-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0004_delete_memorando'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AddField(
            model_name='permiso',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='permisos/'),
        ),
    ]
