# Generated by Django 6.0.6 on 2026-08-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0005_certificado_archivo_permiso_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificado',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
