# Generated by Django 6.0.6 on 2026-06-22 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('area', models.CharField(choices=[('SIN_AREA', 'Sin área'), ('PRODUCCION', 'Producción'), ('MOSTRADOR', 'Mostrador'), ('LIMPIEZA', 'Limpieza'), ('REPOSTERIA', 'Repostería'), ('ASEO', 'Aseo'), ('CAJA', 'Caja')], default='SIN_AREA', max_length=20, verbose_name='Área')),
                ('turno_asociado', models.CharField(blank=True, choices=[('MAÑANA', 'Mañana (4am-2pm)'), ('TARDE', 'Tarde (1pm-11pm)')], max_length=20, null=True, verbose_name='Turno asociado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('fecha_limite', models.DateField(verbose_name='Fecha límite')),
                ('hora_limite', models.TimeField(blank=True, null=True, verbose_name='Hora límite')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('ultimo_cambio_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Último cambio por')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-prioridad', 'fecha_limite'],
                'indexes': [models.Index(fields=['estado', 'empleado'], name='tareas_task_estado_860b88_idx'), models.Index(fields=['fecha_limite'], name='tareas_task_fecha_l_8dbc1c_idx'), models.Index(fields=['empleado', 'estado'], name='tareas_task_emplead_f3ad17_idx'), models.Index(fields=['prioridad'], name='tareas_task_priorid_35a0c7_idx')],
            },
        ),
    ]
