# Generated by Django 6.0.6 on 2026-07-02 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
        ('usuarios', '0006_alter_perfilempleado_id_alter_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tareas_task_estado_860b88_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tareas_task_fecha_l_8dbc1c_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tareas_task_emplead_f3ad17_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tareas_task_priorid_35a0c7_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='area',
            field=models.CharField(choices=[('SIN_AREA', 'Sin área'), ('PRODUCCION', 'Producción'), ('MOSTRADOR', 'Mostrador'), ('LIMPIEZA', 'Limpieza'), ('REPOSTERIA', 'Repostería'), ('ASEO', 'Aseo'), ('CAJA', 'Caja')], default='SIN_AREA', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='usuarios.perfilempleado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=15),
        ),
        migrations.AlterField(
            model_name='task',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='fecha_asignacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='fecha_limite',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='hora_limite',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='turno_asociado',
            field=models.CharField(blank=True, choices=[('MAÑANA', 'Mañana (4am-2pm)'), ('TARDE', 'Tarde (1pm-11pm)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ultimo_cambio_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
