# Generated by Django 6.0.6 on 2026-07-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_alter_task_options_alter_task_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterField(
            model_name='task',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='turno_asociado',
            field=models.CharField(blank=True, choices=[('MAÑANA', 'Mañana (4am-2pm)'), ('TARDE', 'Tarde (1pm-11pm)')], max_length=20, null=True),
        ),
    ]
