# Generated by Django 6.0.6 on 2026-07-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_alter_task_options_alter_task_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='turno_asociado',
            field=models.CharField(blank=True, choices=[('MANANA', 'Mañana'), ('TARDE', 'Tarde'), ('FIJO', 'Fijo')], max_length=20, null=True),
        ),
    ]
