# Generated by Django 6.0.6 on 2026-07-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_alter_task_turno_asociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='evidencia',
            field=models.FileField(blank=True, help_text='Foto o documento opcional como evidencia de finalización', null=True, upload_to='tareas/evidencias/%Y/%m/'),
        ),
    ]
