# Generated by Django 4.2.24 on 2026-09-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorandos', '0001_initial'),
        ('tareas', '0006_task_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='memorando_generado',
            field=models.ForeignKey(blank=True, help_text='Memorando generado automáticamente por acumulación de vencidas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_origen', to='memorandos.memorando'),
        ),
    ]
