# Generated by Django 6.0.6 on 2026-06-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_user_nombre_alter_user_rol_perfilempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilempleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
