# Generated by Django 6.0.6 on 2026-06-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_perfilempleado_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilempleado',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
    ]
