# Generated by Django 4.2.24 on 2026-08-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_migrar_datos_estado_cuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoriacuenta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registroauditoriacuenta',
            name='memorando_consecutivo',
            field=models.CharField(blank=True, help_text='Consecutivo del memorando relacionado, si aplica (ej. MEM-2026-003). No es una FK para evitar acoplar las apps usuarios/memorandos.', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='fecha_primer_acceso',
            field=models.DateTimeField(blank=True, help_text='Se registra la primera vez que el usuario completa su cambio de contraseña obligatorio.', null=True),
        ),
    ]
